### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by tejasm-itpath** [angelleye/IfThenGive#100]
1) What to do when entire goal is deleted with transactions and Givers data?
2) When user cancel billing agreement from PayPal then still our IFThenGive have that agreement details , at that point it will not get used in transaction but user can not cancel or remove billing agreement because while going to delete that BA from the user's My Account page then it throws error as "Preapproved payments are disabled".. So what to do in that situation?

**Comment by tejasm-itpath** [comment]
@angelleye  Pleases see above question

**Comment by angelleye** [comment]
https://angelleye.atlassian.net/browse/ITG-29
