### ISSUE TITLE
Some functionalities to manage

### ISSUE THREAD

**Issue by tejasm-itpath** [angelleye/IfThenGive#103]
1) Progress bar turn to Green when 100% complete.
2) If all the givers are suspended or there are no givers then do not show "Process Donation Button"
3) Add Margin top on Process Donation Button
4) Fix some issues in Select option dropdown in Admin while creating goal.
5) While user is login, And it adds different email then he is adding as itg-extenal_email user but  signed up  for the  login user. We should remove that functionality.
6) If user has already signup in one goal, and signup for another goal then on the admin side Giver status default set to suspended. this need to be fixed.
7) for some user user_meta itg_guest_user is "yes" which is not guest user.
8) View goal page, don't give Editable Title of the Goal
9) Add some processing icons near Process Donation while it is calling an ajax and taking time to check.

**Comment by iMansoorAliKhan** [comment]
http://prntscr.com/j38r7h
the highlighted amount was 1211.09 but after save its 1.0 why???

**Comment by tejasm-itpath** [comment]
@iMansoorAliKhan  @angelleye  For above error we have different issues
