### ISSUE TITLE
How to connect to paypal: Initial Setup : random Issues

### ISSUE THREAD

**Issue by iMansoorAliKhan** [angelleye/IfThenGive#107]
![image](https://user-images.githubusercontent.com/11312949/38658332-23e54dd4-3e3e-11e8-90d1-ea126c23a3d0.png)

**Comment by iMansoorAliKhan** [comment]
Even when added mannual details its showing partially connected???? what exactly that means?

![image](https://user-images.githubusercontent.com/11312949/38658397-60632448-3e3e-11e8-95bb-fd2f0b6c8da4.png)

**Comment by iMansoorAliKhan** [comment]
Also got this error on front-end

Problem with the SSL CA cert (path? access rights?)


Notice: Undefined index: ACK in /wp-content/plugins/angelleye-IfThenGive/public/partials/class-ifthengive-public-display.php on line 504

Notice: Undefined index: L_ERRORCODE0 in wp-content/plugins/angelleye-IfThenGive/public/partials/class-ifthengive-public-display.php on line 510

Notice: Undefined index: L_SHORTMESSAGE0 in wp-content/plugins/angelleye-IfThenGive/public/partials/class-ifthengive-public-display.php on line 510

Notice: Undefined index: L_LONGMESSAGE0 in wp-content/plugins/angelleye-IfThenGive/public/partials/class-ifthengive-public-display.php on line 510
{"Ack":"Failure","ErrorCode":null,"ErrorShort":null,"ErrorLong":null}

**Comment by iMansoorAliKhan** [comment]
Why 2 screens?


![image](https://user-images.githubusercontent.com/11312949/38660002-34660a02-3e45-11e8-9073-f60b2de12131.png)

**Comment by tejasm-itpath** [comment]
@angelleye  @iMansoorAliKhan  
Connect to PayPal issue was because of the PayPal For WooCommerce plugin.
As the PayPal for WooCommerce plugin loads checkout.js on every page of the admin and we are loading partner.js for **Connect with PayPal** button. and because of that it pops up the 2  windows and breaks the functionality.
Jignesh has already created the issue in PayPal for WooCommerce https://github.com/angelleye/paypal-woocommerce/issues/1092
And it will be resolved there.

**Comment by tejasm-itpath** [comment]
@Jignesh has solved the issue in https://github.com/angelleye/paypal-woocommerce/issues/1092
I have tested and it is working now.

**Comment by iMansoorAliKhan** [comment]
if that is the case then why I'm still seeing this?
![image](https://user-images.githubusercontent.com/11312949/38697012-3384cafa-3eaa-11e8-9f41-d662356d6283.png)

And why I'm not able to see my subscribed goals in my account shortcode?
