### ISSUE TITLE
Design Integrations

### ISSUE THREAD

**Issue by tejasm-itpath** [angelleye/IfThenGive#18]

**Comment by tejasm-itpath** [comment]
Most of of the work we have covered in #50

**Comment by angelleye** [comment]
@tejasm-itpath Most of it..??  Does that mean there is still something happening here that isn't included in #50?

**Comment by tejasm-itpath** [comment]
@angelleye  
I forgot that  I have already created issue for design and created #50 and done work on that.
So I have commented here that we have covered every single page and if need for any changes we will do design changes in this plugin.
