### ISSUE TITLE
Channel Initiated Billing Agreements

### ISSUE THREAD

**Issue by angelleye** [angelleye/IfThenGive#29]
In my test case, my sandbox account is not enabled for Express Checkout reference transactions.  As such, I was able to Connect to PayPal, and then I was able to sign up and create a billing agreement as a Giver, but when I tried to process payments with the Fun Button I got an error:

```
    [ERRORS] => Array
        (
            [0] => Array
                (
                    [L_ERRORCODE] => 11452
                    [L_SHORTMESSAGE] => Merchant not enabled for reference transactions
                    [L_LONGMESSAGE] => Merchant not enabled for reference transactions
                    [L_SEVERITYCODE] => Error
                )

            [1] => Array
                (
                    [L_ERRORCODE] => 11451
                    [L_SHORTMESSAGE] => Billing Agreement Id or transaction Id is not valid
                    [L_LONGMESSAGE] => Billing Agreement Id or transaction Id is not valid
                    [L_SEVERITYCODE] => Error
                )

        )
```

What we need to do in order to resolve this is use "Channel Initiated Billing Agreements"...

>You are correct that the standard Billing Agreement will require each merchant to have this feature enabled on their account by contacting PayPal.  However, there is another form of Billing Agreement called a “Channel Initiated Billing Agreement” that can make it so that the merchants do not need to contact PayPal. Channel Initiated Billing Agreements (CIB) are an extension to the standard Billing Agreements.  With CIB, the Billing Agreement is created between a buyer and a third-party facilitator (the partner); the Billing Agreement can then be used to facilitate payments to other merchants.  So, in this scenario, you would now become the owner of the Billing Agreements and you can use this CIB between the buyer and any merchant you have signed up with on your platform.  In short, standard Billing Agreements are used to process Reference Transactions from one buyer to one merchant while the CIB can be used to process payments from one buyer to many merchants.
 

> The flow to set up the Billing Agreement is still the same as before, except the Billing Type in the SetExpressCheckout API call needs to be “ChannelInitiatedBilling”.  Then, when you run the Reference Transaction using CIB, you must set the SUBJECT parameter of the API call to the payer ID of the recipient’s account.  In addition, you must have proper API permissions in place with the recipient to allow you to run Reference Transactions against their account.  These API permissions can be granted using the Integrated Sign Up flow.
>  
> However, do note, that in order to use CIB, there will need to be some vetting and approvals.  If you wish to go down this route, then let us know which account will be used as the facilitator account and we can start working on the process to get the underwriting done.

**Comment by angelleye** [comment]
I don't think we need to change very much here.  In fact, it may be that all we need to change is the Billing Type in our SetExpressCheckout request.

We're already granting API permission for the site owner using our "Connect to PayPal" button, and then we'll use Channel Initiated Billing for the Giver sign up, so the billing agreement will be created with our account, but the future reference transactions would use SUBJECT like we already are.

**Comment by tejasm-itpath** [comment]
I have search for this and 
as per this document https://developer.paypal.com/docs/classic/api/merchant/SetExpressCheckout_API_Operation_NVP/
**L_BILLINGTYPEn** with **MerchantInitiatedBilling**  and **MerchantInitiatedBillingSingleAgreement**  values.
So Can we use **ChannelInitiatedBilling** instead of this ?

**Comment by angelleye** [comment]
@tejasm-itpath I believe it's something they simply haven't documented.  However, we'll need to think about this more.

The way it works is that we would use our own API credentials to create the billing agreements for people, and then we'd also use our own credentials when making reference transaction calls, but we'd pass the site owner PayPal account ID into the SUBJECT parameter, which you're familiar with now.

However, with a WP plugin that we'll be distributing we don't want to include our API credentials, of course.    I'm going to talk to PayPal about other potential options for handling this issue.  It may be that we'll need to store our API credentials on an angelleye.com database, and then pull the values from that when building API requests.

I'll update again when I hear back from PayPal.

**Comment by tejasm-itpath** [comment]
@angelleye  Okay Thanks

**Comment by tejasm-itpath** [comment]
@angelleye 
Facing error
**Channel not enabled for channel initiated billing.**

Solution

> ChannelInitiatedBilling is actually working. I contacted PayPal and they said they have to enable this feature against the account you are using. Regardless of sandbox or live. They said there is not document for ChannelInitiatedBilling at the moment. I have had my accounts enabled and everything works well. So, if you see Channel not enabled for channel initiated billing. message, contact PayPal to enable it for you.

**Comment by tejasm-itpath** [comment]
Added code for in Commit 
https://github.com/angelleye/GiveWhen/commit/235d2b55a7c1efa067ab7621557ef91d21b830dc

we have utilize this filter in the Givehwhen hosted plugin
