### ISSUE TITLE
PayPal Class Library Integration Question

### ISSUE THREAD

**Issue by angelleye** [angelleye/IfThenGive#30]
I'm a little confused about how we have our class library integrated right now.  It looks like you simply added Adaptive.php and Angelleye_PayPal.php under /admin/partials in the plugin..??  

First, I don't know why we have Adaptive added here..??  Second, why didn't we simply install our library using Composer for the plugin?  The way this is now we would not be able to easily update our class library via Composer.  

Ideally, our PHP class would be added to the plugin using composer and autoloaders.  Any reason in particular you didn't do that?

**Comment by angelleye** [comment]
It looks like we also have the PayPal SDK installed, and that one was done via Composer..??  

I feel like this could be cleaned up.  I believe the only thing we need out of PayPal's SDK is the permissions / token generation, right?  On that note, didn't we get that added into our class library in our 3.0 milestone?

**Comment by angelleye** [comment]
@tejasm-itpath In #28 I notice you made an adjustment directly in the Angelleye_PayPal.php class file here. This is a good example of my confusion with our library integration.

If something like this needed to be done in the class library, then we should be able to make that change in our library and easily update here by pulling updates via Composer.

What we're doing here defeats the purpose of having a nice library on GitHub / Packagist / Composer because we're still maintaining them separately.

**Comment by tejasm-itpath** [comment]
@angelleye 
Yes This is good idea but I haven't seen any plugin have whole library via composer so right now after your confirmation we can clean up code which is not required for us in this plugin.

**Comment by angelleye** [comment]
@tejasm-itpath Have you looked at any guides?

* https://wptavern.com/a-narrative-of-using-composer-in-a-wordpress-plugin
* https://roots.io/using-composer-with-wordpress/

**Comment by tejasm-itpath** [comment]
@angelleye  
Right now i have clean up the code in the #31

**Comment by angelleye** [comment]
@tejasm-itpath I know we decided to hold on this, so the label makes sense, but we still have stuff that's already been merged into the dev branch.  Do we need to get that back out?

**Comment by angelleye** [comment]
https://angelleye.atlassian.net/browse/ITG-40
