### ISSUE TITLE
Hosted solution adjustments..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/IfThenGive#33]
Once we're done with this plugin so that it's fully functional for people to install on their own WP site, then we'll be building our hosted version.

The idea with this is that anybody can go to givewhen.com to create goals, and then provide a URL they can give people to sign up for the goal.  Maybe we can also provide an HTML snippet of some sort so that people can embed the HTML signup form into their own site..??

When we build the hosted solution, we'll be using the following features that we were not able to use in the distributed plugin:

- Integrated Sign Up - This should basically be like Login with PayPal + Permissions in a single flow.  This will eliminate the need for a "Connect to PayPal" button because that will be done when they first create their account at GiveWhen.com using the Integrated Signup / Login with PayPal.

- Channel Initiated Billing - The billing agreements will be created with our API credentials and ChannelInitiatedBilling instead of MerchantInitiatedBilling.  We'll use our own credentials for the reference transactions, too, but we'll use the SUBJECT parameter to specify the 3rd party account the payment should go to in that case.  So again, the Permissions step will need to grant us permissions to make reference transaction calls on their behalf.

With all of this in mind, we may need to add some hooks into our plugin so that we can extend it for this custom functionality we'll use on our hosted version of the solution.  I believe the best way to go about this is to do a separate plugin called "GiveWhen Hosted Customization", and within that we'll extend the GiveWhen plugin so that it works as explained above.

**Comment by tejasm-itpath** [comment]
Just like woocommerce have their own action and filter hooks , 
https://docs.woocommerce.com/wc-apidocs/hook-docs.html
We have also actions and filter hooks in our class , so we can extends class and access its method based on objects.
We can think like Givewhen is Woocommerce and GiveWhen hosted version is WC vendors, 
So Just like then we use GiveWhen hooks and also need to create some templates for the front end.
May be we can think more deep in requirements while building it. 

@angelleye

**Comment by tejasm-itpath** [comment]
@angelleye 
I am going to add custom post type capabilities here as we needed givewhen goal creators can access only givewhen custom postype.
