### ISSUE TITLE
PayPal Connect Problems

### ISSUE THREAD

**Issue by angelleye** [angelleye/IfThenGive#55]
If we go through the flow, but we click the X instead of the Continue to Site button, then our Return URL never runs, so our database updates don't trigger.

There is no event trigger in the PayPal Partner / Signup JS that allows us to trigger a function based on the closing of the window.  If we had this we could trigger our return code the same way the other word.

**Comment by angelleye** [comment]
@tejasm-itpath How did OpenCart handle this?  They must have run into the same problem..??

**Comment by tejasm-itpath** [comment]
@angelleye  
Opencart also can't handle that , they are also running into same problem.

**Comment by angelleye** [comment]
https://angelleye.atlassian.net/browse/ITG-38
