### ISSUE TITLE
Option for monthly cap during goal signup.

### ISSUE THREAD

**Issue by angelleye** [angelleye/IfThenGive#70]
Right now people can choose the amount they want to donate when signing up, but they can't choose a total amount per month.  For example, if the goal is a "home run" you might only want to give for up to 5 home runs in a month, but not more.

**Comment by angelleye** [comment]
This can turn into a rather lengthy issue to deal with depending on how far we go with it.  Might need to save this for a 1.1.0.

**Comment by angelleye** [comment]
Consider the following:

- User signs up for a goal for "home runs" at $10 per home run, with a max monthly set to $50.
- Player hits 8 home runs during a month, so this would be $80.

So how should this be treated?  Do we just cap it at $50, and then we start at $0 the next month, losing out on 3 home runs worth of donations?  Or do we carry that over?

- We hit our process button the first 5 times, and $10 is taken each time.
- The next 3 times we hit the button, it sees the cap has been reached, so it adds $10 to a "running balance" field in the database.  So we end up with $30 in our running balance at the end of this month.
- We could then have a CRON running to process all running balances.  (This step alone would need more planning to figure out how we'd handle all the different sign-up dates.  Do we do this based on sign-up date, or do we just start all of these based on the 1st of the month?)

So then we also have other things to consider like...

- Should the Giver be able to choose whether or not we can carry over funds or not?  
- Our reports and emails will need to be updated.  Right now they return "successful" and "failed" transactions, but we'll need to also separate the "added to running balance" transactions as well.
- This will also need to be updated in our filters in the post type pages, etc.

**Comment by tejasm-itpath** [comment]
@angelleye  Above both commit is belongs to #71

**Comment by angelleye** [comment]
@tejasm-itpath Looks like this stuff was already merged into dev, but I don't think it's ready yet..??

**Comment by angelleye** [comment]
https://angelleye.atlassian.net/browse/ITG-37
