### ISSUE TITLE
My Account

### ISSUE THREAD

**Issue by angelleye** [angelleye/IfThenGive#76]
I signed up for a goal and I created an account during the process.  After sign-up, I was able to click the My Account link to view the account dashboard, but I don't see anywhere that I can view what Goals I'm signed up for and see my give/donation history..??

**Comment by tejasm-itpath** [comment]
@angelleye 
If you put [ifthengive_account] shotcode then you can see My Account page for the Givers.
Like this https://www.screencast.com/t/8MRcpslu

- Transaction tab will display all the transactions list for his signup goals.
- Goals tab will display all goals givers signed up https://www.screencast.com/t/pQvBngE0U
- Giver can adjust amount from front end and also make it suspend too from Goals tab.
- In the Account tab , he can cancel billing agreement for the signed up goals.  https://www.screencast.com/t/erXcsAod
