### ISSUE TITLE
Live Mode error on clean install.

### ISSUE THREAD

**Issue by angelleye** [angelleye/IfThenGive#80]
On clean install when I first go into the settings I'm seeing an error:

![image](https://user-images.githubusercontent.com/629241/37643178-baae7f28-2bed-11e8-8519-237360c0dcb4.png)

We shouldn't be displaying any error at this point.  We haven't even tried to set anything up yet.

**Comment by tejasm-itpath** [comment]
https://www.screencast.com/t/xzMHguA9p9cu
We need to manage new error response comes with the Live environment from PayPal ISU

**Comment by angelleye** [comment]
@tejasm-itpath I'm getting this PHP warning now:

>Warning: json_decode() expects parameter 1 to be string, array given in /home/angelley/sandbox_woocommerce/wp-content/plugins/angelleye-ifthengive/admin/partials/class-ifthengive-connect_paypal.php on line 351

![image](https://user-images.githubusercontent.com/629241/37700034-10897fc2-2cb8-11e8-913a-4ab5033d54e1.png)
