### ISSUE TITLE
Create Setting for upload logo and brand name for Express Checkout PayPal

### ISSUE THREAD

**Issue by tejasm-itpath** [angelleye/IfThenGive#83]

**Comment by angelleye** [comment]
@tejasm-itpath As discussed in Slack, we should have logo settings for 2 different parameters.  SetExpressCheckout can include both of the following:

HDRIMG - 750x90
LOGOIMG - 190x60

We should have separate options to set an image for each of those, and we need to add tool-tips to let people know what size each should be and how to use the SSL hosting service if they need it.
