### ISSUE TITLE
Need to make changes to improve code

### ISSUE THREAD

**Issue by tejasm-itpath** [angelleye/IfThenGive#87]
While developing the plugin we have created and used customized functions but instead we can use WordPress core functions and make execution more feasible

**Comment by tejasm-itpath** [comment]
1) We need to manage all the html for front end as template. so developers can add/modify their template.
2 )Need to add action and filter hook where it is necessary.
3) Remove repeated code and make code management just like WooCommerce code have.
4) Add comments to the top of the functions and parameters.

**Comment by angelleye** [comment]
https://angelleye.atlassian.net/browse/ITG-34
