### ISSUE TITLE
Amounts being processed are incorrect!?

### ISSUE THREAD

**Issue by angelleye** [angelleye/IfThenGive#90]
* https://mail.google.com/mail/u/0/#inbox/160f73a27e565e8f

>The paypal billing agreement is capturing an amount of 14,707 for a 5.00 pledge.
>
>![image](https://user-images.githubusercontent.com/629241/37870202-b0fc7b00-2f95-11e8-888f-64359c1ad65f.png)

**Comment by tejasm-itpath** [comment]
@angelleye 
I was unable to reproduce the error mentioned above but 
I have change some code that might creates this problem. 
After this commit I hope above error will not seen.

**Comment by angelleye** [comment]
I haven't seen this happening in any of our latest tests, so I'll go ahead and close this issue now.
