### ISSUE TITLE
Payment processing tracker.

### ISSUE THREAD

**Issue by ghost** [angelleye/IfThenGive#93]
Right now, if we hit the button to process payments for a goal, and it fails/halts for any reason before completing every payment, there's no way for us to re-start where it left off.  

We need to think about adding a tracking system so that each time a goal is hit and payments are processed, each one is flagged as "completed" for that one specific batch.  If the entire batch completes then all get reset so they'll be included on the next batch.

**Comment by angelleye** [comment]
@tejasm-itpath I'd like to review how you tested this.  Did you actually import a bunch of givers into a goal and set some of them up to fail so that you could then run this and test it?  I'd like to see a video of this functionality.

**Comment by tejasm-itpath** [comment]
@angelleye  Basic video of Donation Process
https://www.screencast.com/t/vCVT21Wl6JN
