### ISSUE TITLE
Process Management in PHP

### ISSUE THREAD

**Issue by tejasm-itpath** [angelleye/IfThenGive#99]
Right now on every loop or every process , we are storing value in wp_option table and if the option like itg_transactions_in_process = 'yes' then we can not process other goal. 

we have to find some way that we can manage that simultaneously. Like dividing whole foreach loop in small piece  of tasks and then Process individually on ajax like updraft plugin does.

**Comment by tejasm-itpath** [comment]
- click Process Donation
- 73% process
- again click Process Donation
- click "Continue with remaining"

Bug - Mail is not sent to admin for previous completed txns.
	  Remaninig txns emails are	received
	  PDF also not generating

**Comment by angelleye** [comment]
https://angelleye.atlassian.net/browse/ITG-30
